### ISSUE TITLE
Should this repo be included in Palm?

### ISSUE THREAD

**Issue by mtyaka** [openedx/xblock-skill-tagging#8]
@pkulkark @navinkarkera 

The Build-Test-Release Working Group is preparing to cut branches for Palm, the next Open edX release. The cut will happen on April 11th.

The [`openedx.yml`](https://github.com/openedx/xblock-skill-tagging/blob/b322d8b13b66a69326b8fad77ccba4631dbdece9/openedx.yaml#L20) currently says that this repo should "maybe" be included in the next release.

Is the repo ready to be included in Palm? Or should we wait until Quince, scheduled to be released in December?

**Comment by navinkarkera** [comment]
@mtyaka  The repo is ready but I am not sure about what including in Palm release means here. Since this repo is a plugin which should only be installed by users if they want to utilize skill/tag verification forms.

**Comment by mtyaka** [comment]
@navinkarkera It only means that an `open-release/palm.master` branch will be created (and `open-release/palm.<n>` tags when actual releases happen), so that users that are using Palm can quickly find a compatible version of this repo. It doesn't mean that it will be included and/or enabled in a standard installation by default.

**Comment by mtyaka** [comment]
I opened a [PR](https://github.com/openedx/xblock-skill-tagging/pull/9) to remove the `maybe: true` line from `openedx.yaml`.

**Comment by navinkarkera** [comment]
@mtyaka Thanks.

**Comment by cmltaWt0** [comment]
I'm closing the issue since the repo is included in Palm+ releases.
